routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');

        Route::get('pemiliks/{pemilik}/generate-account', 'PemilikController@generate')->name('pemiliks.generate');

        Route::resource('bloks', BlokController::class);
        Route::resource('komoditis', KomoditiController::class);
        Route::resource('detail-komoditis', DetailKomoditiController::class);
        Route::resource('tokos', TokoController::class);
        Route::resource('detail-tokos', DetailTokoController::class);
        Route::resource('pemiliks', PemilikController::class);
        Route::resource('pengunjungs', PengunjungController::class);


        // Pemilik
        Route::get('toko', 'Pemilik\TokoController@index')->name('pemilik.toko.index');
        Route::get('rule', 'RuleController@index')->name('rule.index');
        Route::get('rule/toko', 'RuleController@toko')->name('rule.toko');

    });

app/Models/DetailToko.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;

class DetailToko extends Model
{
    use Searchable;

    protected $fillable = [
        'toko_id',
        'pemilik_id',
        'detail_komoditi_id',
        'profill_toko',
        'deskripsi',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'detail_toko';

    public function toko()
    {
        return $this->belongsTo(Toko::class);
    }

    public function detailKomoditi()
    {
        return $this->belongsTo(DetailKomoditi::class);
    }

    public function pemilik()
    {
        return $this->belongsTo(Pemilik::class);
    }

    public function pengunjungs()
    {
        return $this->hasMany(Pengunjung::class);
    }
}

app/Http/Controllers/DetailTokoController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Models\Toko;
use App\Models\Pemilik;
use App\Models\DetailToko;
use Illuminate\Http\Request;
use App\Models\DetailKomoditi;
use App\Models\DetailTokoKomoditi;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\DetailTokoStoreRequest;
use App\Http\Requests\DetailTokoUpdateRequest;

class DetailTokoController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', DetailToko::class);

        $search = $request->get('search', '');

        // $detailTokos = DetailToko::search($search)
        //     ->latest()
        //     ->paginate(5);

        $detailTokos = DetailToko::select([
            '*',
            DB::raw(
                "( select group_concat(komoditi) from detail_toko_komoditi where detail_toko_id = detail_toko.id ) as komoditi "
            )
        ])
        ->with(['toko'])
        ->latest()
        ->paginate(5);

        return view('app.detail_tokos.index', compact('detailTokos', 'search'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', DetailToko::class);

        // $tokos = Toko::pluck('id', 'id', 'komiditi_id');
        $tokos = Toko::all();
        
        $detailKomoditis = DetailKomoditi::all();
//        $pemiliks = Pemilik::pluck('nik', 'id');
        $pemiliks = Pemilik::select("*", DB::raw("CONCAT(pemilik.nik,' (',pemilik.nama,')') as display_name"))
        ->pluck('display_name', 'id');

        return view(
            'app.detail_tokos.create',
            compact('tokos', 'detailKomoditis', 'pemiliks')
        );
    }

    /**
     * @param \App\Http\Requests\DetailTokoStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(DetailTokoStoreRequest $request)
    {
        $this->authorize('create', DetailToko::class);

        $validated = $request->validated();
        if ($request->hasFile('profill_toko')) {
            $validated['profill_toko'] = $request
                ->file('profill_toko')
                ->store('public');
        }

        DB::beginTransaction();

        $detailToko = DetailToko::create($validated);

        foreach ($request->komoditi as $key => $value) {
            $detailKomoditi = DetailKomoditi::where('id', $value)->first();
            $detail_toko_komoditi = [
                'toko_id' => $request->toko_id,
                'detail_toko_id' => $detailToko->id,
                'detail_komoditi_id' => $detailKomoditi->id,
                'komoditi' => $detailKomoditi->nama
            ];

            DetailTokoKomoditi::create($detail_toko_komoditi);
        }

        DB::commit();

        // DB::rollback();

        return redirect()
            ->route('detail-tokos.edit', $detailToko)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\DetailToko $detailToko
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, DetailToko $detailToko)
    {
        $this->authorize('view', $detailToko);

        // $detailToko = DB::select("
        //     select 
        //         *,
        //         ( select group_concat(komoditi) from detail_toko_komoditi where detail_toko_id = ? ) as komoditi 
        //     from detail_toko where id = ?
        // ", [$detailToko->id, $detailToko->id]);

        $detailToko = DetailToko::select([
            '*',
            DB::raw(
                "( select group_concat(komoditi) from detail_toko_komoditi where detail_toko_id = detail_toko.id ) as komoditi "
            )
        ])
        ->where('id', $detailToko->id)
        ->with(['toko'])
        ->first();

        // $detailToko = collect($detailToko);

        return view('app.detail_tokos.show', compact('detailToko'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\DetailToko $detailToko
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, DetailToko $detailToko)
    {
        $this->authorize('update', $detailToko);

        // $tokos = Toko::pluck('id', 'id');
        $tokos = Toko::all();
        $detailKomoditis = DetailKomoditi::pluck('nama', 'id');
        $pemiliks = Pemilik::select("*", DB::raw("CONCAT(pemilik.nik,' (',pemilik.nama,')') as display_name"))
        ->pluck('display_name', 'id');

        return view(
            'app.detail_tokos.edit',
            compact('detailToko', 'tokos', 'detailKomoditis', 'pemiliks')
        );
    }

    /**
     * @param \App\Http\Requests\DetailTokoUpdateRequest $request
     * @param \App\Models\DetailToko $detailToko
     * @return \Illuminate\Http\Response
     */
    public function update(
        DetailTokoUpdateRequest $request,
        DetailToko $detailToko
    ) {
        $this->authorize('update', $detailToko);

        $validated = $request->validated();

        if ($request->hasFile('profill_toko')) {
            if ($detailToko->profill_toko) {
                Storage::delete($detailToko->profill_toko);
            }

            $validated['profill_toko'] = $request
                ->file('profill_toko')
                ->store('public');
        }

        DB::beginTransaction();

        $detailToko->update($validated);

        DetailTokoKomoditi::where('detail_toko_id', $detailToko->id)->delete();

        foreach ($request->komoditi as $key => $value) {
            $detailKomoditi = DetailKomoditi::where('id', $value)->first();
            $detail_toko_komoditi = [
                'toko_id' => $request->toko_id,
                'detail_toko_id' => $detailToko->id,
                'detail_komoditi_id' => $detailKomoditi->id,
                'komoditi' => $detailKomoditi->nama
            ];

            DetailTokoKomoditi::create($detail_toko_komoditi);
        }

        DB::commit();

        return redirect()
            ->route('detail-tokos.edit', $detailToko)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\DetailToko $detailToko
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, DetailToko $detailToko)
    {
        $this->authorize('delete', $detailToko);

        if ($detailToko->profill_toko) {
            Storage::delete($detailToko->profill_toko);
        }

        $detailToko->delete();

        return redirect()
            ->route('detail-tokos.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/detail_tokos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('detail-tokos.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.detail_toko.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('detail-tokos.store') }}"
                has-files
                class="mt-4"
            >
                @include('app.detail_tokos.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('detail-tokos.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

@section('js-script')
    <script>
        $('select[name=toko_id]').on('change', function(){
            let value = $(this).val()

            console.log(value);

            $.get('{{ route('api.services.detail-komoditi') }}', {id: value}, function(response){
                $('#komoditi-container').html(response.view)
            })
        })
    </script>
@endsection

resources/views/app/detail_tokos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('detail-tokos.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.detail_toko.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('detail-tokos.update', $detailToko) }}"
                has-files
                class="mt-4"
            >
                @include('app.detail_tokos.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('detail-tokos.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('detail-tokos.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

@section('js-script')
    <script>
        $(function() {
            $.get('{{ route('api.services.detail-komoditi') }}', {id: '{{ $detailToko->toko_id }}', detail_toko_id: {{ $detailToko->id }}, action: 'edit' }, function(response){
                $('#komoditi-container').html(response.view)
            })  
        })
    </script>
@endsection

resources/views/app/detail_tokos/form-inputs.blade.php
@php $editing = isset($detailToko) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12 col-lg-6">
        <x-inputs.select name="toko_id" label="Toko" required>
            @php $selected = old('toko_id', ($editing ? $detailToko->toko_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Toko</option>
            @foreach($tokos as $value => $label)
            <option value="{{ $label->id }}" {{ $selected == $label->id ? 'selected' : '' }} >{{ $label->id }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12 col-lg-6">
        @php
            $label = 'Detail Komoditi';
            $name = $label;
        @endphp
        @include('components.inputs.partials.label')
        <div id="komoditi-container" class="form-group"></div>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12 col-lg-8">
        <x-inputs.select name="pemilik_id" label="Pemilik" required>
            @php $selected = old('pemilik_id', ($editing ? $detailToko->pemilik_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Pemilik</option>
            @foreach($pemiliks as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12 col-lg-4">
        <div
            x-data="imageViewer('{{ $editing && $detailToko->profill_toko ? \Storage::url($detailToko->profill_toko) : '' }}')"
        >
            <x-inputs.partials.label
                name="profill_toko"
                label="Profill Toko"
            ></x-inputs.partials.label
            ><br />

            <!-- Show the image -->
            <template x-if="imageUrl">
                <img
                    :src="imageUrl"
                    class="object-cover rounded border border-gray-200"
                    style="width: 100px; height: 100px;"
                />
            </template>

            <!-- Show the gray box when image is not available -->
            <template x-if="!imageUrl">
                <div
                    class="border rounded border-gray-200 bg-gray-100"
                    style="width: 100px; height: 100px;"
                ></div>
            </template>

            <div class="mt-2">
                <input
                    type="file"
                    name="profill_toko"
                    id="profill_toko"
                    @change="fileChosen"
                />
            </div>

            @error('profill_toko') @include('components.inputs.partials.error')
            @enderror
        </div>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.textarea name="deskripsi" label="Deskripsi" required
            >{{ old('deskripsi', ($editing ? $detailToko->deskripsi : ''))
            }}</x-inputs.textarea
        >
    </x-inputs.group>
</div>

resources/views/app/detail_tokos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <div style="display: flex; justify-content: space-between;">
                <h4 class="card-title">
                    @lang('crud.detail_toko.index_title')
                </h4>
            </div>

            <div class="searchbar mt-4 mb-5">
                <div class="row">
                    <div class="col-md-6">
                        <form>
                            <div class="input-group">
                                <input
                                    id="indexSearch"
                                    type="text"
                                    name="search"
                                    placeholder="{{ __('crud.common.search') }}"
                                    value="{{ $search ?? '' }}"
                                    class="form-control"
                                    autocomplete="off"
                                />
                                <div class="input-group-append">
                                    <button
                                        type="submit"
                                        class="btn btn-primary"
                                    >
                                        <i class="icon ion-md-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6 text-right">
                        @can('create', App\Models\DetailToko::class)
                        <a
                            href="{{ route('detail-tokos.create') }}"
                            class="btn btn-primary"
                        >
                            <i class="icon ion-md-add"></i>
                            @lang('crud.common.create')
                        </a>
                        @endcan
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.detail_toko.inputs.toko_id')
                            </th>
                            <th class="text-left">
                                Komoditi
                            </th>                            
                            <th class="text-left">
                                @lang('crud.detail_toko.inputs.detail_komoditi_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.detail_toko.inputs.pemilik_id')
                            </th>
                            <th class="text-left">
                                Profile Toko
                            </th>
                            <th class="text-left">
                                @lang('crud.detail_toko.inputs.deskripsi')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($detailTokos as $detailToko)
                        <tr>
                            <td>
                                {{ optional($detailToko->toko)->id ?? '-' }}
                            </td>
                            <td>
                                {{ optional($detailToko->toko->komoditi)->nama ?? '-' }}
                            </td>                            
                            <td>
                                {{ \Str::limit($detailToko->komoditi, 25)
                                ?? '-' }}
                            </td>
                            <td>
                                {{ optional($detailToko->pemilik)->nik ?? '-' }} ( {{ optional($detailToko->pemilik)->nama ?? '-' }} )
                            </td>
                            <td>
                                <x-partials.thumbnail
                                    src="{{ $detailToko->profill_toko ? \Storage::url($detailToko->profill_toko) : '' }}"
                                />
                            </td>
                            <td>{{ $detailToko->deskripsi ?? '-' }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $detailToko)
                                    <a
                                        href="{{ route('detail-tokos.edit', $detailToko) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $detailToko)
                                    <a
                                        href="{{ route('detail-tokos.show', $detailToko) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $detailToko)
                                    <form
                                        action="{{ route('detail-tokos.destroy', $detailToko) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6">{!! $detailTokos->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/detail_tokos/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('detail-tokos.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.detail_toko.show_title')
            </h4>

            {{-- {{ dd($detailToko) }} --}}
            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.detail_toko.inputs.toko_id')</h5>
                    <span>{{ optional($detailToko->toko)->id ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.detail_toko.inputs.detail_komoditi_id')</h5>
                    <span
                        >{{ $detailToko->komoditi ?? '-' }}</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.detail_toko.inputs.pemilik_id')</h5>
                    <span
                        >{{ optional($detailToko->pemilik)->nik ?? '-' }} ({{ optional($detailToko->pemilik)->nama ?? '-' }})</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.detail_toko.inputs.profill_toko')</h5>
                    <x-partials.thumbnail
                        src="{{ $detailToko->profill_toko ? \Storage::url($detailToko->profill_toko) : '' }}"
                        size="150"
                    />
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.detail_toko.inputs.deskripsi')</h5>
                    <span>{{ $detailToko->deskripsi ?? '-' }}</span>
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('detail-tokos.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\DetailToko::class)
                <a
                    href="{{ route('detail-tokos.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection