routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');

        Route::get('pemiliks/{pemilik}/generate-account', 'PemilikController@generate')->name('pemiliks.generate');

        Route::resource('bloks', BlokController::class);
        Route::resource('komoditis', KomoditiController::class);
        Route::resource('detail-komoditis', DetailKomoditiController::class);
        Route::resource('tokos', TokoController::class);
        Route::resource('detail-tokos', DetailTokoController::class);
        Route::resource('pemiliks', PemilikController::class);
        Route::resource('pengunjungs', PengunjungController::class);


        // Pemilik
        Route::get('toko', 'Pemilik\TokoController@index')->name('pemilik.toko.index');
        Route::get('rule', 'RuleController@index')->name('rule.index');
        Route::get('rule/toko', 'RuleController@toko')->name('rule.toko');

    });

app/Models/Pengunjung.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;

class Pengunjung extends Model
{
    use Searchable;

    protected $fillable = ['detail_toko_id', 'nama', 'komentar', 'rating'];

    protected $searchableFields = ['*'];

    protected $table = 'pengunjung';

    public function detailToko()
    {
        return $this->belongsTo(DetailToko::class);
    }
}

app/Http/Controllers/PengunjungController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengunjung;
use App\Models\DetailToko;
use Illuminate\Http\Request;
use App\Http\Requests\PengunjungStoreRequest;
use App\Http\Requests\PengunjungUpdateRequest;

class PengunjungController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', Pengunjung::class);

        $search = $request->get('search', '');

        $pengunjungs = Pengunjung::search($search)
            ->latest()
            ->paginate(5);

        return view('app.pengunjungs.index', compact('pengunjungs', 'search'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', Pengunjung::class);

        $detailTokos = DetailToko::pluck('toko_id', 'id');

        return view('app.pengunjungs.create', compact('detailTokos'));
    }

    /**
     * @param \App\Http\Requests\PengunjungStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(PengunjungStoreRequest $request)
    {
        $this->authorize('create', Pengunjung::class);

        $validated = $request->validated();

        $pengunjung = Pengunjung::create($validated);

        return redirect()
            ->route('pengunjungs.edit', $pengunjung)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Pengunjung $pengunjung
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Pengunjung $pengunjung)
    {
        $this->authorize('view', $pengunjung);

        return view('app.pengunjungs.show', compact('pengunjung'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Pengunjung $pengunjung
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Pengunjung $pengunjung)
    {
        $this->authorize('update', $pengunjung);

        $detailTokos = DetailToko::pluck('toko_id', 'id');

        return view(
            'app.pengunjungs.edit',
            compact('pengunjung', 'detailTokos')
        );
    }

    /**
     * @param \App\Http\Requests\PengunjungUpdateRequest $request
     * @param \App\Models\Pengunjung $pengunjung
     * @return \Illuminate\Http\Response
     */
    public function update(
        PengunjungUpdateRequest $request,
        Pengunjung $pengunjung
    ) {
        $this->authorize('update', $pengunjung);

        $validated = $request->validated();

        $pengunjung->update($validated);

        return redirect()
            ->route('pengunjungs.edit', $pengunjung)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Pengunjung $pengunjung
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Pengunjung $pengunjung)
    {
        $this->authorize('delete', $pengunjung);

        $pengunjung->delete();

        return redirect()
            ->route('pengunjungs.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/pengunjungs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('pengunjungs.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.pengunjung.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('pengunjungs.store') }}"
                class="mt-4"
            >
                @include('app.pengunjungs.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('pengunjungs.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/pengunjungs/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('pengunjungs.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.pengunjung.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('pengunjungs.update', $pengunjung) }}"
                class="mt-4"
            >
                @include('app.pengunjungs.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('pengunjungs.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('pengunjungs.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/pengunjungs/form-inputs.blade.php
@php $editing = isset($pengunjung) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="detail_toko_id" label="Detail Toko" required>
            @php $selected = old('detail_toko_id', ($editing ? $pengunjung->detail_toko_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Detail Toko</option>
            @foreach($detailTokos as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.text
            name="nama"
            label="Nama"
            value="{{ old('nama', ($editing ? $pengunjung->nama : '')) }}"
            maxlength="255"
            required
        ></x-inputs.text>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.text
            name="komentar"
            label="Komentar"
            value="{{ old('komentar', ($editing ? $pengunjung->komentar : '')) }}"
            maxlength="255"
            required
        ></x-inputs.text>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="rating" label="Rating">
            @php $selected = old('rating', ($editing ? $pengunjung->rating : '')) @endphp
            <option value="1" {{ $selected == '1' ? 'selected' : '' }} >1</option>
            <option value="2" {{ $selected == '2' ? 'selected' : '' }} >2</option>
            <option value="3" {{ $selected == '3' ? 'selected' : '' }} >3</option>
            <option value="4" {{ $selected == '4' ? 'selected' : '' }} >4</option>
            <option value="5" {{ $selected == '5' ? 'selected' : '' }} >5</option>
        </x-inputs.select>
    </x-inputs.group>
</div>

resources/views/app/pengunjungs/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <div style="display: flex; justify-content: space-between;">
                <h4 class="card-title">@lang('crud.pengunjung.index_title')</h4>
            </div>

            <div class="searchbar mt-4 mb-5">
                <div class="row">
                    <div class="col-md-6">
                        <form>
                            <div class="input-group">
                                <input
                                    id="indexSearch"
                                    type="text"
                                    name="search"
                                    placeholder="{{ __('crud.common.search') }}"
                                    value="{{ $search ?? '' }}"
                                    class="form-control"
                                    autocomplete="off"
                                />
                                <div class="input-group-append">
                                    <button
                                        type="submit"
                                        class="btn btn-primary"
                                    >
                                        <i class="icon ion-md-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6 text-right">
                        @can('create', App\Models\Pengunjung::class)
                        <a
                            href="{{ route('pengunjungs.create') }}"
                            class="btn btn-primary"
                        >
                            <i class="icon ion-md-add"></i>
                            @lang('crud.common.create')
                        </a>
                        @endcan
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.pengunjung.inputs.detail_toko_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.pengunjung.inputs.nama')
                            </th>
                            <th class="text-left">
                                @lang('crud.pengunjung.inputs.komentar')
                            </th>
                            <th class="text-left">
                                @lang('crud.pengunjung.inputs.rating')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($pengunjungs as $pengunjung)
                        <tr>
                            <td>
                                {{ optional($pengunjung->detailToko)->toko_id ??
                                '-' }}
                            </td>
                            <td>{{ $pengunjung->nama ?? '-' }}</td>
                            <td>{{ $pengunjung->komentar ?? '-' }}</td>
                            <td>{{ $pengunjung->rating ?? '-' }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $pengunjung)
                                    <a
                                        href="{{ route('pengunjungs.edit', $pengunjung) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $pengunjung)
                                    <a
                                        href="{{ route('pengunjungs.show', $pengunjung) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $pengunjung)
                                    <form
                                        action="{{ route('pengunjungs.destroy', $pengunjung) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="5">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">{!! $pengunjungs->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/pengunjungs/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('pengunjungs.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.pengunjung.show_title')
            </h4>

            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.pengunjung.inputs.detail_toko_id')</h5>
                    <span
                        >{{ optional($pengunjung->detailToko)->toko_id ?? '-'
                        }}</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.pengunjung.inputs.nama')</h5>
                    <span>{{ $pengunjung->nama ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.pengunjung.inputs.komentar')</h5>
                    <span>{{ $pengunjung->komentar ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.pengunjung.inputs.rating')</h5>
                    <span>{{ $pengunjung->rating ?? '-' }}</span>
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('pengunjungs.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\Pengunjung::class)
                <a
                    href="{{ route('pengunjungs.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection